steps:
  - id: build-v68-preprod
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - Dockerfile.v68-preprod
      - --tag
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${BUILD_ID}
      - .
  - id: push-v68-preprod
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${BUILD_ID}
images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${BUILD_ID}
options:
  logging: CLOUD_LOGGING_ONLY
