import type {Catalog,Product} from "./data.js";
const W="5493417234000"; const money=new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS",maximumFractionDigits:0});
export function catalogPage(c:Catalog){const brands=[...new Set(c.products.map(p=>p.brand.name))], cats=[...new Set(c.products.flatMap(p=>p.categorySlugs))]; return shell("Farmagreen Rosario | Catálogo 2.0","Catálogo FarmaGreen WhatsApp-first",`
<section class="benefits"><span>Retiro coordinado en Rosario</span><span>Consulta directa por WhatsApp</span><span>Ofertas destacadas</span></section>
<section class="hero"><div><p class="k">Farmagreen Rosario</p><h1>Elegí mejor. Consultá simple.</h1><p>Catálogo dermocosmético y saludable con página por producto, búsqueda rápida y conversación directa.</p><div class="hero-actions"><a href="#productos">Ver catálogo</a><a href="${wa("Hola Farmagreen Rosario, quiero consultar por el catálogo.")}">WhatsApp</a></div></div><aside><b>${c.totalProducts}</b><span>productos</span><small>${brands.length} marcas · ${date(c.syncedAt)}</small></aside></section>
<nav class="navrail"><button data-brand="Todas">Todas</button>${brands.map(b=>`<button data-brand="${e(b)}">${e(b)}</button>`).join("")}</nav>
<section class="toolbox"><input id="search" placeholder="Buscar marca, producto o necesidad"><div class="catline"><button data-cat="Todas">Todas</button>${cats.slice(0,9).map(x=>`<button data-cat="${e(x)}">${label(x)}</button>`).join("")}</div></section>
<section id="productos" class="catalog-head"><h2>Productos</h2><p id="count"></p></section><section class="grid" id="grid">${c.products.slice(0,36).map(card).join("")}</section>
<script>window.__FG2=${json({products:c.products})}</script><script type="module" src="/app.js"></script>`)}
export function productPage(p:Product, rel:Product[]){return shell(`${p.name} | Farmagreen Rosario`,p.description.slice(0,155),`<nav class="crumb"><a href="/catalogo">Catálogo</a><span>/</span><span>${e(p.brand.name)}</span></nav><article class="pdp"><div class="photo"><img src="${e(p.images.detail)}" alt="${e(p.name)}"></div><div class="buybox"><p class="k">${e(p.brand.name)}</p><h1>${e(p.name)}</h1><p class="line">${e(p.line)} · ${label(p.primaryCategory)}</p>${price(p)}<a class="cta" href="${wa(`Hola Farmagreen Rosario, quiero consultar por ${p.brand.name} - ${p.name}.`)}">Consultar este producto por WhatsApp</a><section><h2>Detalle</h2><p>${e(p.description)}</p></section></div></article><section class="catalog-head"><h2>Similares</h2><p>Misma marca o necesidad.</p></section><section class="grid compact">${rel.map(card).join("")}</section><script type="application/ld+json">${json({"@context":"https://schema.org","@type":"Product",name:p.name,image:p.images.detail,description:p.description,brand:{"@type":"Brand",name:p.brand.name},offers:{"@type":"Offer",priceCurrency:"ARS",price:p.offerPrice||p.listPrice,availability:"https://schema.org/LimitedAvailability"}})}</script>`)}
export const notFound=()=>shell("No encontrado | Farmagreen","Producto no encontrado",`<section class="empty"><h1>No encontramos ese producto</h1><a href="/catalogo">Volver al catálogo</a></section>`);
function shell(title:string,desc:string,body:string){return`<!doctype html><html lang="es-AR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${e(title)}</title><meta name="description" content="${e(desc)}"><link rel="icon" href="/logo_farmagreen.png"><link rel="stylesheet" href="/styles.css"></head><body><header class="top"><a href="/catalogo"><img src="/logo_farmagreen.png" alt="Farmagreen"></a><a class="topwa" href="${wa("Hola Farmagreen Rosario, quiero consultar.")}">WhatsApp</a></header><main>${body}</main><a class="float" href="${wa("Hola Farmagreen Rosario, quiero hacer una consulta.")}">☎</a></body></html>`}
function card(p:Product){return`<article class="card"><a class="pic" href="/producto/${e(p.slug)}"><img src="${e(p.images.card)}" alt="${e(p.name)}"></a><p>${e(p.brand.name)}</p><h3><a href="/producto/${e(p.slug)}">${e(p.name)}</a></h3><small>${e(p.line)}</small>${price(p)}<a class="ask" href="${wa(`Hola Farmagreen Rosario, quiero consultar por ${p.brand.name} - ${p.name}.`)}">Consultar</a></article>`}
function price(p:Product){return`<div class="price">${p.discountPercent>0?`<b>${Math.round(p.discountPercent)}% OFF</b><s>${money.format(p.listPrice)}</s>`:""}<strong>${money.format(p.offerPrice||p.listPrice)}</strong></div>`}
const wa=(m:string)=>`https://wa.me/${W}?text=${encodeURIComponent(m)}`; const e=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]||c)); const json=(v:unknown)=>JSON.stringify(v).replace(/</g,"\\u003c"); const label=(v:string)=>e(v.replace(/-/g," ").replace(/\b\w/g,l=>l.toUpperCase())); const date=(v:string)=>new Intl.DateTimeFormat("es-AR",{dateStyle:"short"}).format(new Date(v));
