import type {Catalog,Product} from "./data.js";
const BASE=(process.env.PUBLIC_BASE_PATH||"").replace(/\/$/,"");
const W="5493417234000"; const money=new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS",maximumFractionDigits:0});
export function catalogPage(c:Catalog){const brands=[...new Set(c.products.map(p=>p.brand.name))], cats=[...new Set(c.products.flatMap(p=>p.categorySlugs))]; return shell("Farmagreen Rosario | Catálogo 2.0","Catálogo FarmaGreen WhatsApp-first",`
<section class="benefits"><span>Retiro coordinado en Rosario</span><span>Consulta directa por WhatsApp</span><span>Ofertas destacadas</span></section>
<nav class="quicknav" aria-label="Accesos rápidos"><a href="#marcas">Marcas</a><a href="#categorias">Categorías</a><a href="#productos">Productos</a><a href="${wa("Hola Farmagreen Rosario, quiero consultar por el catálogo.")}">WhatsApp</a></nav>
<section class="hero"><div><p class="k">Farmagreen Rosario</p><h1>Elegí mejor. Consultá simple.</h1><p>Catálogo dermocosmético y saludable con página por producto, búsqueda rápida y conversación directa.</p><div class="hero-actions"><a href="#productos">Ver catálogo</a><a href="${wa("Hola Farmagreen Rosario, quiero consultar por el catálogo.")}">WhatsApp</a></div></div><aside><b>${c.totalProducts}</b><span>productos</span><small>${brands.length} marcas · ${date(c.syncedAt)}</small></aside></section>
<section class="filterdeck"><div class="railcard"><div class="railhead" id="marcas"><h2>Marcas</h2><p>Entrá rápido por laboratorio o línea.</p></div><nav class="navrail"><button data-brand="Todas">Todas</button>${brands.map(b=>`<button data-brand="${e(b)}">${e(b)}</button>`).join("")}</nav></div><section class="toolbox"><div class="toolhead"><div><p class="toolk">Buscador</p><h2>Filtrá como en desktop</h2></div><button id="clearFilters" type="button">Limpiar filtros</button></div><input id="search" placeholder="Buscar marca, producto o necesidad"><div class="railhead" id="categorias"><h2>Categorías</h2><p>Misma utilidad en mobile y escritorio.</p></div><div class="catline"><button data-cat="Todas">Todas</button>${cats.map(x=>`<button data-cat="${e(x)}">${label(x)}</button>`).join("")}</div></section></section>
<section id="productos" class="catalog-head"><h2>Productos</h2><p id="count"></p></section><section class="grid" id="grid">${c.products.slice(0,36).map(card).join("")}</section>
<script>window.__FG2=${json({base:BASE,products:c.products})}</script><script type="module" src="${u("/app.js")}"></script>`)}
export function productPage(p:Product, rel:Product[]){return shell(`${p.name} | Farmagreen Rosario`,p.description.slice(0,155),`<nav class="crumb"><a href="${u("/catalogo/")}">Catálogo</a><span>/</span><span>${e(p.brand.name)}</span></nav><article class="pdp"><div class="photo"><img src="${e(p.images.detail)}" alt="${e(p.name)}"></div><div class="buybox"><p class="k">${e(p.brand.name)}</p><h1>${e(p.name)}</h1><p class="line">${e(p.line)} · ${label(p.primaryCategory)}</p>${price(p)}<a class="cta" href="${wa(`Hola Farmagreen Rosario, quiero consultar por ${p.brand.name} - ${p.name}.`)}">Consultar este producto por WhatsApp</a><section><h2>Detalle</h2><p>${e(p.description)}</p></section></div></article><section class="catalog-head"><h2>Similares</h2><p>Misma marca o necesidad.</p></section><section class="grid compact">${rel.map(card).join("")}</section><script type="application/ld+json">${json({"@context":"https://schema.org","@type":"Product",name:p.name,image:p.images.detail,description:p.description,brand:{"@type":"Brand",name:p.brand.name},offers:{"@type":"Offer",priceCurrency:"ARS",price:p.offerPrice||p.listPrice,availability:"https://schema.org/LimitedAvailability"}})}</script>`)}
export const notFound=()=>shell("No encontrado | Farmagreen","Producto no encontrado",`<section class="empty"><h1>No encontramos ese producto</h1><a href="${u("/catalogo/")}">Volver al catálogo</a></section>`);
function shell(title:string,desc:string,body:string){return`<!doctype html><html lang="es-AR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${e(title)}</title><meta name="description" content="${e(desc)}"><link rel="icon" href="${u("/logo_farmagreen.png")}"><link rel="stylesheet" href="${u("/styles.css")}"></head><body><header class="top"><a href="${u("/catalogo/")}" class="brandmark"><img src="${u("/logo_farmagreen.png")}" alt="Farmagreen"></a><div class="toplinks"><a href="${u("/catalogo/#marcas")}">Marcas</a><a href="${u("/catalogo/#categorias")}">Categorías</a><a href="${u("/catalogo/#productos")}">Productos</a></div><a class="topwa" href="${wa("Hola Farmagreen Rosario, quiero consultar.")}">${waIcon()}<span>WhatsApp</span></a></header><main>${body}</main><a class="float" href="${wa("Hola Farmagreen Rosario, quiero hacer una consulta.")}" aria-label="Consultar por WhatsApp">${waIcon()}</a></body></html>`}
function card(p:Product){return`<article class="card"><a class="pic" href="${u(`/producto/${p.slug}/`)}"><img src="${e(p.images.card)}" alt="${e(p.name)}"></a><p>${e(p.brand.name)}</p><h3><a href="${u(`/producto/${p.slug}/`)}">${e(p.name)}</a></h3><small>${e(p.line)}</small>${price(p)}<a class="ask" href="${wa(`Hola Farmagreen Rosario, quiero consultar por ${p.brand.name} - ${p.name}.`)}">Consultar</a></article>`}
function price(p:Product){return`<div class="price">${p.discountPercent>0?`<b>${Math.round(p.discountPercent)}% OFF</b><s>${money.format(p.listPrice)}</s>`:""}<strong>${money.format(p.offerPrice||p.listPrice)}</strong></div>`}
function waIcon(){return`<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M19.1 4.9A9.86 9.86 0 0 0 12.06 2C6.59 2 2.13 6.42 2.13 11.89c0 1.75.46 3.45 1.34 4.94L2 22l5.32-1.39a9.96 9.96 0 0 0 4.74 1.2h.01c5.47 0 9.93-4.42 9.93-9.89a9.8 9.8 0 0 0-2.9-7.02Zm-7.04 15.24h-.01a8.3 8.3 0 0 1-4.23-1.16l-.3-.18-3.16.82.84-3.08-.2-.32a8.2 8.2 0 0 1-1.28-4.33c0-4.54 3.72-8.24 8.29-8.24 2.21 0 4.3.86 5.87 2.42a8.18 8.18 0 0 1 2.42 5.83c0 4.55-3.72 8.24-8.24 8.24Zm4.53-6.18c-.25-.12-1.47-.73-1.7-.81-.23-.08-.39-.12-.56.12-.17.24-.64.81-.79.98-.15.17-.3.19-.55.06-.25-.12-1.07-.39-2.04-1.24-.75-.67-1.27-1.49-1.42-1.74-.15-.24-.02-.37.11-.49.11-.11.25-.29.37-.44.12-.14.16-.24.24-.41.08-.17.04-.31-.02-.44-.06-.12-.56-1.34-.76-1.84-.2-.47-.4-.41-.56-.42h-.48c-.17 0-.44.06-.67.31-.23.24-.88.86-.88 2.11s.9 2.45 1.02 2.62c.12.17 1.77 2.7 4.29 3.79.6.26 1.07.41 1.44.52.61.19 1.17.16 1.61.1.49-.07 1.47-.6 1.68-1.19.21-.58.21-1.09.15-1.19-.06-.1-.23-.16-.48-.29Z"/></svg>`}
const u=(p:string)=>`${BASE}${p}`; const wa=(m:string)=>`https://wa.me/${W}?text=${encodeURIComponent(m)}`; const e=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]||c)); const json=(v:unknown)=>JSON.stringify(v).replace(/</g,"\\u003c"); const label=(v:string)=>e(v.replace(/-/g," ").replace(/\b\w/g,l=>l.toUpperCase())); const date=(v:string)=>new Intl.DateTimeFormat("es-AR",{dateStyle:"short"}).format(new Date(v));
