import http from "node:http";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { catalog, product, similar } from "./data.js";
import { catalogPage, notFound, productPage } from "./render.js";
import { catalogPageV67, catalogV67, notFoundPageV67, productPageV67, productV67, similarV67 } from "./render-v67.js";
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),".."), PUB=path.join(ROOT,"public");
const PORT=Number(process.env.PORT||8094), HOST=process.env.HOST||"127.0.0.1", DEFAULT_ROUTE=process.env.DEFAULT_ROUTE||"/catalogo/";
const mime:Record<string,string>={".css":"text/css; charset=utf-8",".js":"text/javascript; charset=utf-8",".png":"image/png"};
export function app(){return http.createServer(async(req,res)=>{try{const u=new URL(req.url||"/",`http://${req.headers.host||"local"}`), p=normalize(decodeURIComponent(u.pathname)); if(p==="/")return red(res,DEFAULT_ROUTE); if(p==="/catalogo-v6-7")return html(res,catalogPageV67(await catalogV67(),u.searchParams)); if(p.startsWith("/producto-v6-7/")){const found=await productV67(p.slice("/producto-v6-7/".length)); return found?html(res,productPageV67(found,await similarV67(found))):html(res,notFoundPageV67(),404)} if(p==="/catalogo")return html(res,catalogPage(await catalog())); if(p==="/api/catalog")return json(res,await catalog()); if(p.startsWith("/producto/")){const found=await product(p.slice(10)); return found?html(res,productPage(found,await similar(found))):html(res,notFound(),404)} if(["/styles.css","/styles-v6-5.css","/styles-v6-6.css","/styles-v6-7.css","/app.js","/app-v6-7.js","/logo_farmagreen.png"].includes(p)){const fp=path.join(PUB,p); return bin(res,await fs.readFile(fp),mime[path.extname(fp)]||"application/octet-stream")} txt(res,"Acceso denegado.",403)}catch(e){console.error(e); txt(res,"Error local.",500)}})}
function h(x:Record<string,string>={}){return{"content-security-policy":"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self'; img-src 'self' data: https://storage.googleapis.com https://gpsfarma.com https://9dejulio.gpsfarma.com; connect-src 'self'; base-uri 'self'; form-action 'self'; frame-ancestors 'self'","x-content-type-options":"nosniff","x-frame-options":"SAMEORIGIN","referrer-policy":"strict-origin-when-cross-origin","permissions-policy":"camera=(), microphone=(), geolocation=(), payment=()","x-robots-tag":"noindex,nofollow",...x}}
function red(r:http.ServerResponse,l:string){r.writeHead(302,h({location:l,"cache-control":"no-store"}));r.end()} function html(r:http.ServerResponse,b:string,s=200){r.writeHead(s,h({"content-type":"text/html; charset=utf-8","cache-control":"no-cache"}));r.end(b)} function json(r:http.ServerResponse,b:unknown){r.writeHead(200,h({"content-type":"application/json; charset=utf-8"}));r.end(JSON.stringify(b))} function txt(r:http.ServerResponse,b:string,s=200){r.writeHead(s,h({"content-type":"text/plain; charset=utf-8"}));r.end(b)} function bin(r:http.ServerResponse,b:Buffer,t:string){r.writeHead(200,h({"content-type":t,"cache-control":"no-cache"}));r.end(b)}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)) app().listen(PORT,HOST,()=>console.log(`FarmaGreen 2.0 DNA: http://${HOST}:${PORT}${DEFAULT_ROUTE}`));
function normalize(p:string){return p.length>1&&p.endsWith("/")?p.slice(0,-1):p}
